<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE changelog [
<!ELEMENT changelog (version+)>
<!ELEMENT version (by*,packetinfo,sectorinfo,POFinfo,aliasinfo,change+)>
<!ELEMENT packetinfo (filename*,url*)>
<!ELEMENT sectorinfo (filename*,url*)>
<!ELEMENT POFinfo (filename*,url*)>
<!ELEMENT aliasinfo (filename*,url*)>
<!ELEMENT filename (#PCDATA)>
<!ELEMENT url (#PCDATA)>
<!ELEMENT by (#PCDATA)>
<!ELEMENT change (#PCDATA)>
<!ATTLIST version current CDATA #IMPLIED>
<!ATTLIST version releasedate CDATA #IMPLIED>
<!ATTLIST version releasetime CDATA #IMPLIED>
<!ATTLIST version airac CDATA #IMPLIED>
<!ATTLIST by title CDATA #IMPLIED>
<!ATTLIST packetinfo filerev CDATA #IMPLIED>
<!ATTLIST packetinfo releasedate CDATA #IMPLIED>
<!ATTLIST sectorinfo filerev CDATA #IMPLIED>
<!ATTLIST sectorinfo releasedate CDATA #IMPLIED>
<!ATTLIST POFinfo filerev CDATA #IMPLIED>
<!ATTLIST POFinfo releasedate CDATA #IMPLIED>
<!ATTLIST aliasinfo filerev CDATA #IMPLIED>
<!ATTLIST aliasinfo releasedate CDATA #IMPLIED>
<!ATTLIST change affected CDATA #IMPLIED>
]>
 <changelog>
  <version current="1" releasedate="24 Aug 2016" releasetime="1472061600" airac="1608">
   <by title="Facility Engineer">James Waltz</by>
   <packetinfo filerev="5.12" releasedate="08/24/2016">
    <filename>New Student Package v5.12</filename>
    <url>https://github.com/ZDV-ARTCC/ZDV_FacilityEngineering/raw/master/Releases/New%20Student%20Package%20v5.12.zip</url>
   </packetinfo>
   <sectorinfo filerev="5.12" releasedate="08/24/2016">
    <filename>ZDV ARTCC Sector v5.12</filename>
    <url>https://github.com/ZDV-ARTCC/ZDV_FacilityEngineering/raw/master/Releases/ZDV_ARTCC_Sector_5.12.zip</url>
   </sectorinfo>
   <POFinfo filerev="4.4" releasedate="08/24/2016">
    <filename>ZDV POF File v4.4</filename>
    <url>https://github.com/ZDV-ARTCC/ZDV_FacilityEngineering/raw/master/Releases/VZDVv4.4.zip</url>
   </POFinfo>
   <aliasinfo filerev="2.1.4" releasedate="1/16/2013">
    <filename>ZDV Alias File v2.1.4</filename>
    <url>https://github.com/ZDV-ARTCC/ZDV_FacilityEngineering/raw/master/Releases/zdv_alias_v2.1.4.zip</url>
   </aliasinfo>
	 <change affected="ALL">Nav Data updated to AIRAC 1608</change>
	 <change affected="ALL">Text changes to diagrams menu</change>
	 <change affected="ALL">POF File updated for ZKC frequency changes</change>
	 <change affected="ALL">POF File fixed CPR_GND entry</change>
  </version>
  <version releasedate="27 May 2016" releasetime="1464397233 " airac="1605">
   <by title="Facility Engineer">James Waltz</by>
   <packetinfo filerev="5.11" releasedate="5/27/2016">
    <filename>New Student Package v5.11</filename>
    <url>https://github.com/ZDV-ARTCC/ZDV_FacilityEngineering/raw/master/Releases/New%20Student%20Package%20v5.11.zip</url>
   </packetinfo>
   <sectorinfo filerev="5.11" releasedate="5/27/2016">
    <filename>ZDV ARTCC Sector v5.11</filename>
    <url>https://github.com/ZDV-ARTCC/ZDV_FacilityEngineering/raw/master/Releases/ZDV_ARTCC_Sector_5.11.zip</url>
   </sectorinfo>
   <POFinfo filerev="4.3" releasedate="1/24/2016">
    <filename>ZDV POF File v4.3</filename>
    <url>https://github.com/ZDV-ARTCC/ZDV_FacilityEngineering/raw/master/Releases/VZDVv4.3.zip</url>
   </POFinfo>
   <aliasinfo filerev="2.1.4" releasedate="1/16/2013">
    <filename>ZDV Alias File v2.1.4</filename>
    <url>https://github.com/ZDV-ARTCC/ZDV_FacilityEngineering/raw/master/Releases/zdv_alias_v2.1.4.zip</url>
   </aliasinfo>
	 <change affected="ALL">Nav Data updated to AIRAC 1605</change>
	 <change affected="ALL">MIAs updated</change>
  </version>
  <version releasedate="22 Mar 2016" releasetime="1458685701" airac="1603">
   <by title="Facility Engineer">James Waltz</by>
   <packetinfo filerev="5.10" releasedate="3/22/2016">
    <filename>New Student Package v5.10</filename>
    <url>https://github.com/ZDV-ARTCC/ZDV_FacilityEngineering/raw/master/Releases/New%20Student%20Package%20v5.10.zip</url>
   </packetinfo>
   <sectorinfo filerev="5.10" releasedate="3/22/2016">
    <filename>ZDV ARTCC Sector v5.10</filename>
    <url>https://github.com/ZDV-ARTCC/ZDV_FacilityEngineering/raw/master/Releases/ZDV_ARTCC_Sector_5.10.zip</url>
   </sectorinfo>
   <POFinfo filerev="4.3" releasedate="1/24/2016">
    <filename>ZDV POF File v4.3</filename>
    <url>https://github.com/ZDV-ARTCC/ZDV_FacilityEngineering/raw/master/Releases/VZDVv4.3.zip</url>
   </POFinfo>
   <aliasinfo filerev="2.1.4" releasedate="1/16/2013">
    <filename>ZDV Alias File v2.1.4</filename>
    <url>https://github.com/ZDV-ARTCC/ZDV_FacilityEngineering/raw/master/Releases/zdv_alias_v2.1.4.zip</url>
   </aliasinfo>
	<change affected="ALL">Nav Data updated to AIRAC 1603</change>
	<change affected="ALL">INI File Updated in New Students Package</change>
  </version>
   <version releasedate="24 Jan 2016" releasetime="1453679999" airac="1601">
   <by title="Facility Engineer">James Waltz</by>
   <packetinfo filerev="5.9" releasedate="1/24/2016">
    <filename>New Student Package v5.9</filename>
    <url>https://github.com/ZDV-ARTCC/ZDV_FacilityEngineering/raw/master/Releases/New%20Student%20Package%20v5.9.zip</url>
   </packetinfo>
   <sectorinfo filerev="5.9" releasedate="1/24/2016">
    <filename>ZDV ARTCC Sector v5.9</filename>
    <url>https://github.com/ZDV-ARTCC/ZDV_FacilityEngineering/raw/master/Releases/ZDV_ARTCC_Sector_5.9.zip</url>
   </sectorinfo>
   <POFinfo filerev="4.3" releasedate="1/24/2016">
    <filename>ZDV POF File v4.3</filename>
    <url>https://github.com/ZDV-ARTCC/ZDV_FacilityEngineering/raw/master/Releases/VZDVv4.3.zip</url>
   </POFinfo>
   <aliasinfo filerev="2.1.4" releasedate="1/16/2013">
    <filename>ZDV Alias File v2.1.4</filename>
    <url>https://github.com/ZDV-ARTCC/ZDV_FacilityEngineering/raw/master/Releases/zdv_alias_v2.1.4.zip</url>
   </aliasinfo>
	<change affected="KEGE">KEGE Airport Diagram Updated</change>
	<change affected="KBJC">KBJC Airport Diagram Updated</change>
	<change affected="ZDV">Split line for ZLA sector 6 and 36 added</change>
	<change affected="KEGE">EKR1 updated to EKR2 and corrected</change>
	<change affected="ALL">Nav Data updated to AIRAC 1601</change>
	<change affected="ALL">POF File Updated</change>
  </version>
  <version releasedate="19 Oct 2015" releasetime="1445255000" airac="1509">
   <by title="Assistant Facility Engineer">James Waltz</by>
   <packetinfo filerev="5.8" releasedate="10/19/2015">
    <filename>New Student Package v5.8</filename>
    <url>https://github.com/ZDV-ARTCC/ZDV_FacilityEngineering/raw/master/Releases/New%20Student%20Package%20v5.8.zip</url>
   </packetinfo>
   <sectorinfo filerev="5.8" releasedate="10/19/2015">
    <filename>ZDV ARTCC Sector v5.8</filename>
    <url>https://github.com/ZDV-ARTCC/ZDV_FacilityEngineering/raw/master/Releases/ZDV_ARTCC_Sector_5.8.zip</url>
   </sectorinfo>
   <POFinfo filerev="4.2" releasedate="9/20/2015">
    <filename>ZDV POF File v4.2</filename>
    <url>https://github.com/ZDV-ARTCC/ZDV_FacilityEngineering/raw/master/Releases/VZDVv4.2.zip</url>
   </POFinfo>
   <aliasinfo filerev="2.1.4" releasedate="1/16/2013">
    <filename>ZDV Alias File v2.1.4</filename>
    <url>https://github.com/ZDV-ARTCC/ZDV_FacilityEngineering/raw/master/Releases/zdv_alias_v2.1.4.zip</url>
   </aliasinfo>
	<change affected="ALL">Revised CTR Splits</change>
  </version>
  <version releasedate="20 Sep 2015" releasetime="1442777391" airac="1509">
   <by title="Facility Engineer">Casey Diers</by>
   <packetinfo filerev="5.7" releasedate="9/20/2015">
    <filename>New Student Package v5.7</filename>
    <url>https://github.com/ZDV-ARTCC/ZDV_FacilityEngineering/raw/master/Releases/New%20Student%20Package%20v5.7.zip</url>
   </packetinfo>
   <sectorinfo filerev="5.7" releasedate="9/20/2015">
    <filename>ZDV ARTCC Sector v5.7</filename>
    <url>https://github.com/ZDV-ARTCC/ZDV_FacilityEngineering/raw/master/Releases/ZDV_ARTCC_Sector_5.7.zip</url>
   </sectorinfo>
   <POFinfo filerev="4.2" releasedate="9/20/2015">
    <filename>ZDV POF File v4.2</filename>
    <url>https://github.com/ZDV-ARTCC/ZDV_FacilityEngineering/raw/master/Releases/VZDVv4.2.zip</url>
   </POFinfo>
   <aliasinfo filerev="2.1.4" releasedate="1/16/2013">
    <filename>ZDV Alias File v2.1.4</filename>
    <url>https://github.com/ZDV-ARTCC/ZDV_FacilityEngineering/raw/master/Releases/zdv_alias_v2.1.4.zip</url>
   </aliasinfo>
	<change affected="ALL">Update Sector File for AIRAC 1509</change>
	<change affected="ALL">POF Updates</change>
	<change affected="KASE">Update KASE airport diagram</change>
	<change affected="KCOS">Update KCOS MVAs</change>
  </version>
 <version releasedate="26 May 2015" releasetime="1432695628" airac="1505">
   <by title="Facility Engineer">Casey Diers</by>
   <packetinfo filerev="5.6" releasedate="5/26/2015">
    <filename>New Student Package v5.6</filename>
    <url>https://github.com/ZDV-ARTCC/ZDV_FacilityEngineering/raw/master/Releases/New%20Student%20Package%20v5.6.zip</url>
   </packetinfo>
   <sectorinfo filerev="5.6" releasedate="5/26/2015">
    <filename>ZDV ARTCC Sector v5.6</filename>
    <url>https://github.com/ZDV-ARTCC/ZDV_FacilityEngineering/raw/master/Releases/ZDV_ARTCC_Sector_5.6.zip</url>
   </sectorinfo>
   <POFinfo filerev="4.1" releasedate="3/22/2015">
    <filename>ZDV POF File v4.1</filename>
    <url>https://github.com/ZDV-ARTCC/ZDV_FacilityEngineering/raw/master/Releases/VZDVv4.1.zip</url>
   </POFinfo>
   <aliasinfo filerev="2.1.4" releasedate="1/16/2013">
    <filename>ZDV Alias File v2.1.4</filename>
    <url>https://github.com/ZDV-ARTCC/ZDV_FacilityEngineering/raw/master/Releases/zdv_alias_v2.1.4.zip</url>
   </aliasinfo>
	<change affected="ALL">Updated VORs, NDBs, fixes, and airways for 1505.</change>
	<change affected="KCOS">Update COS MVAs</change>
  </version>
 <version releasedate="22 March 2015" releasetime="1427077707" airac="1503">
   <by title="Facility Engineer">Casey Diers</by>
   <packetinfo filerev="5.5" releasedate="3/22/2015">
    <filename>New Student Package v5.5</filename>
    <url>https://github.com/ZDV-ARTCC/ZDV_FacilityEngineering/raw/master/Releases/New%20Student%20Package%20v5.5.zip</url>
   </packetinfo>
   <sectorinfo filerev="5.5" releasedate="3/22/2015">
    <filename>ZDV ARTCC Sector v5.5</filename>
    <url>https://github.com/ZDV-ARTCC/ZDV_FacilityEngineering/raw/master/Releases/ZDV_ARTCC_Sector_5.5.zip</url>
   </sectorinfo>
   <POFinfo filerev="4.1" releasedate="3/22/2015">
    <filename>ZDV POF File v4.1</filename>
    <url>https://github.com/ZDV-ARTCC/ZDV_FacilityEngineering/raw/master/Releases/VZDVv4.1.zip</url>
   </POFinfo>
   <aliasinfo filerev="2.1.4" releasedate="1/16/2013">
    <filename>ZDV Alias File v2.1.4</filename>
    <url>https://github.com/ZDV-ARTCC/ZDV_FacilityEngineering/raw/master/Releases/zdv_alias_v2.1.4.zip</url>
   </aliasinfo>
	<change>Updated VORs, NDBs, FIXs, and Airways to 1503 AIRAC.</change>
	<change affected="KPUB">Update KPUB to reflect the new runway north of old runway 08L/26R. Runways renamed accordingly.</change>
	<change affected="ALL">Update ZAB Center Splits diagram to correctly reflect the changes to their sectorization that they implemented in January of 2015.</change>
  </version>
 <version releasedate="23 November 2014" releasetime="1416770296" airac="1412">
   <by title="Facility Engineer">Casey Diers</by>
   <packetinfo filerev="5.4" releasedate="11/23/14">
    <filename>New Student Package v5.4</filename>
    <url>http://denartcc.org/fe/New Student Package v5.4.zip</url>
   </packetinfo>
   <sectorinfo filerev="5.4" releasedate="11/23/14">
    <filename>ZDV ARTCC Sector v5.4</filename>
    <url>http://denartcc.org/fe/ZDV_ARTCC_Sector_5.4.zip</url>
   </sectorinfo>
   <POFinfo filerev="4.01" releasedate="5/16/2011">
    <filename>ZDV POF File v4.01</filename>
    <url>http://denartcc.org/fe/VZDVv4.01.zip</url>
   </POFinfo>
   <aliasinfo filerev="2.1.4" releasedate="1/16/2013">
    <filename>ZDV Alias File v2.1.4</filename>
    <url>http://denartcc.org/fe/zdv_alias_v2.1.4.zip</url>
   </aliasinfo>
	<change>Updated VORs, NDBs, FIXs, and Airways to 1412 AIRAC.</change>
	<change affected="KDEN, D01">DANDD SIX becomes DANDD SEVEN.</change>
	<change affected="KDEN, D01">JAGGR TWO becomes JAGGR THREE.</change>
	<change affected="KDEN, D01">BRYCC ONE becomes BRYCC THREE.</change>
	<change affected="KDEN, D01">EPKEE TWO becomes EPKEE THREE.</change>
	<change affected="KDEN, D01">STAKR TWO becomes STAKR THREE.</change>
	<change affected="KDEN, D01">SPAZZ TWO becomes SPAZZ THREE.</change>
	<change affected="KDEN, D01">SOLAR TWO becomes SOLAR THREE.</change>
	<change affected="KDEN, D01">CONNR TWO becomes CONNR THREE.</change>
	<change affected="KDEN, D01">COORZ TWO becomes COORZ THREE.</change>
	<change affected="KDEN, D01">FOOOT TWO becomes FOOOT THREE.</change>
	<change affected="KDEN, D01">YAMMI TWO becomes YAMMI THREE.</change>
	<change affected="KDEN, D01">RIKKK TWO becomes RIKKK THREE</change>
	<change affected="KDEN, D01">BAYLR TWO becomes BAYLR THREE.</change>
	<change affected="KDEN, D01">CREDE TWO becomes CREDE THREE.</change>
	<change affected="KDEN, D01">FRNCH TWO becomes FRNCH THREE.</change>
	<change affected="KDEN, D01">MOLTN TWO becomes MOLTN THREE.</change>
	<change affected="KDEN, D01">PEEKK TWO becomes PEEKK THREE.</change>
	<change affected="KDEN, D01">ZPLYN TWO becomes ZPLYN THREE.</change>
	<change affected="KDEN, D01">PIKES FIVE  becomes PIKES SEVEN.</change>
	<change affected="KDEN, D01">PLAINS FIVE becomes PLAINS SEVEN.</change>
	<change affected="KDEN, D01">YELLO SEVEN becomes YELLO NINE.</change>
	<change affected="KDEN, D01">ROCKI NINE becomes ROCKI TWO.</change>
	<change affected="KDEN, D01">EEONS TWO becomes EEONS FOUR.</change>
	<change affected="KDEN, D01">EMMYS TWO becomes EMMYS FOUR.</change>
	<change affected="KDEN, D01">EXTAN TWO becomes EXTAN FOUR.</change>
	<change affected="KDEN, D01">YOKES TWO becomes YOKES FOUR.</change>
	<change affected="KAPA, D01">PUFFR TWO becomes PUFFR FOUR.</change>
	<change affected="KAPA, D01">SKARF TWO becomes SKARF THREE.</change>
	<change affected="KEGE, D01">GYPSM FOUR becomes GYPSM FIVE.</change>
	<change affected="KCPR, D01">ALCOS FOUR becomes ALCOS FIVE.</change>
	<change affected="KDEN, D01">JMPRS ONE becomes JMPRS TWO.</change>
	<change affected="KDEN, D01">ANCHR TWO becomes ANCHR THREE.</change>
	<change affected="KDEN, D01">KIPPR TWO becomes KIPPR THREE.</change>
	<change affected="KDEN, D01">KOHOE TWO becomes KOHOE THREE.</change>
	<change affected="KDEN, D01">WAHUU ONE becomes WAHUU TWO.</change>
	<change affected="KAPA, D01">ADDED FOOOT THREE to KAPA diagram list.</change>
	<change affected="KAPA, D01">DUNNN ONE becomes DUNNN TWO.</change>
	<change affected="KBJC, D01">Updated runway numbers at KBJC.</change>
  </version>
 <version releasedate="14 September 2013" releasetime="1379192376" airac="1309">
   <by title="Facility Engineer">Casey Diers</by>
   <packetinfo filerev="5.3" releasedate="9/13/2013">
    <filename>New Student Package v5.3</filename>
    <url>http://denartcc.org/fe/New Student Package v5.3.zip</url>
   </packetinfo>
   <sectorinfo filerev="5.3" releasedate="9/13/2013">
    <filename>ZDV ARTCC Sector v5.3</filename>
    <url>http://denartcc.org/fe/ZDV_ARTCC_Sector_5.3.zip</url>
   </sectorinfo>
   <POFinfo filerev="4.01" releasedate="5/16/2011">
    <filename>ZDV POF File v4.01</filename>
    <url>http://denartcc.org/fe/VZDVv4.01.zip</url>
   </POFinfo>
   <aliasinfo filerev="2.1.4" releasedate="1/16/2013">
    <filename>ZDV Alias File v2.1.4</filename>
    <url>http://denartcc.org/fe/zdv_alias_v2.1.4.zip</url>
   </aliasinfo>
	<change>Updated VORs, NDBs, FIXs, and Airways to 1309 AIRAC.</change>
	<change affected="KDEN, D01">BAYLR ONE becomes BAYLR TWO</change>
	<change affected="KDEN, D01">BRYCC ONE becomes BRYCC TWO</change>
	<change affected="KDEN, D01">CONNR ONE becomes CONNR TWO</change>
	<change affected="KDEN, D01">COORZ ONE becomes COORZ TWO</change>
	<change affected="KDEN, D01">EEONS TWO becomes EEONS THREE</change>
	<change affected="KDEN, D01">EMMYS TWO becomes EMMYS THREE</change>
	<change affected="KDEN, D01">EPKEE ONE becomes EPKEE TWO</change>
	<change affected="KDEN, D01">EXTAN TWO becomes EXTAN THREE</change>
	<change affected="KDEN, D01">FOOOT ONE becomes FOOOT TWO</change>
	<change affected="KDEN, D01">RIKKK ONE becomes RIKKK TWO</change>
	<change affected="KDEN, D01">SOLAR ONE becomes SOLAR TWO</change>
	<change affected="KDEN, D01">SPAZZ ONE becomes SPAZZ TWO</change>
	<change affected="KDEN, D01">STAKR ONE becomes STAKR TWO</change>
	<change affected="KDEN, D01">YAMMI ONE becomes YAMMI TWO</change>
	<change affected="KDEN, D01">YOKES ONE becomes YOKES TWO</change>
	<change affected="KBJC, D01">KBJC Airport Section added to accommodate BJC specific maps.</change>
	<change affected="KBJC, D01">New SID at KBJC: DUNNN ONE</change>
	<change affected="D01">New RNAV specific video maps added throughout.</change>
	<change affected="D01">Airport dividers in airport list added for reading clarity.</change>
	<change affected="D01">D01 Class B Map Updated</change>
	<change affected="D01">D01 MVAs separated from D01 Primary Video Map for clarity</change>
	<change affected="D01">New D01 Roads and Landmarks Map.  This data split from Class B map for additional clarity.</change>
	<change affected="D01">New D01 Emergency Obstacle Video Map added</change>
	<change affected="D01">D01 STARs RNAV L/N and L/S headers now clickable and gives a simplified overview of all Land North or Land South procedures.</change>
	<change affected="D01">New D01 STAR header called L/N/S.  Is clickable and gives a simplified overview of all Land North / South RNAV STAR procedures.</change>
	<change affected="D01">New D01 SID header called South.  Is clickable and gives a simplified overview of all Land South RNAV SID procedures.</change>
	<change affected="D01">New D01 SID header called North.  Is clickable and gives a simplified overview of all Land North RNAV SID procedures.</change>
	<change affected="D01">New D01 header called DEN RNAV-ILS Transitions and has several video maps, organized by corresponding approach runway, which show the connector paths from the RNAV arrivals to the ILS approaches.</change>
	<change affected="D01">New D01 SID header called D01 SAT RNAV SIDS.  Is clickable and gives a simplified overview of D01 satellite airport SID procedures.  At this time, appears to have extraneous data.  This may incorporate future procedures not yet published.</change>
	<change affected="D01">New KAPA header called RNAV STARs APA.  Is clickable and gives a simplified overview of all KAPA STAR procedures.  At this time, appears to have extraneous and / or erroneous data.  This may incorporate future procedures not yet published.</change>
	<change affected="D01">New KBJC header called RNAV STARs BJC.  Is clickable and gives a simplified overview of all KAPA STAR procedures.  At this time, appears to have extraneous and / or erroneous data.  This may incorporate future procedures not yet published.</change>
	<change affected="D01">Reverted center MVA colors to their color from before 10-13-12.  This makes them a less predominate color.</change>
	<change affected="D01">Created a new color group so that Tracon MVAs can be more easily manipulated and set their colors to match the center MVA colors.</change>
	<change affected="D01">Removed D01 Emergency Obstacle Video Map.</change>
  </version>
  <version releasedate="7 July 2013" releasetime="1373597211" airac="1307">
   <by title="Facility Engineer">Casey Diers</by>
   <packetinfo filerev="5.2" releasedate="7/11/2013">
    <filename>New Student Package v5.2</filename>
    <url>http://denartcc.org/fe/New Student Package v5.2.zip</url>
   </packetinfo>
   <sectorinfo filerev="5.2" releasedate="7/11/2013">
    <filename>ZDV ARTCC Sector v5.2</filename>
    <url>http://denartcc.org/fe/ZDV_ARTCC_Sector_5.2.zip</url>
   </sectorinfo>
   <POFinfo filerev="4.01" releasedate="5/16/2011">
    <filename>ZDV POF File v4.01</filename>
    <url>http://denartcc.org/fe/VZDVv4.01.zip</url>
   </POFinfo>
   <aliasinfo filerev="2.1.4" releasedate="1/16/2013">
    <filename>ZDV Alias File v2.1.4</filename>
    <url>http://denartcc.org/fe/zdv_alias_v2.1.4.zip</url>
   </aliasinfo>
	<change>Updated VORs, NDBs, FIXs, and Airways to 1307 AIRAC.</change>
	<change>Changed magnetic variation of entire file to 8deg east (from 8.0)deg east.  This is due to the resurveying of KDEN (2015).</change>
   	<change affected="KEAR">Added back in the KEAR shelf, which modified DEN_CTR's boundary with ZMP.  It got omitted somewhere along the way, but has always been active.</change>
	<change affected="KDEN, D01">Added BAYLR ONE</change>
	<change affected="KDEN, D01">ANCHR ONE becomes ANCHR TWO</change>
	<change affected="KDEN, D01">CREDE ONE becomes CREDE TWO</change>
	<change affected="KDEN, D01">FRNCH ONE becomes FRNCH TWO</change>
	<change affected="KDEN, D01">JAGGR ONE becomes JAGGR TWO</change>
	<change affected="KDEN, D01">KOHOE ONE becomes KOHOE TWO</change>
	<change affected="KDEN, D01">MOLTN ONE becomes MOLTN TWO</change>
	<change affected="KDEN, D01">PEEKK ONE becomes PEEKK TWO</change>
	<change affected="KDEN, D01">ZPLYN ONE becomes ZPLYN TWO</change>
	<change affected="KDEN, D01">PIKES FIVE radials updated due to the resurveying of KDEN (2015).</change>
	<change affected="KDEN, D01">PLAIN FIVE radials updated due to the resurveying of KDEN (2015).</change>
	<change affected="KDEN, D01">YELLO SEVEN radials updated due to the resurveying of KDEN (2015).</change>
	<change affected="KDEN, D01">ROCKI EIGHT becomes ROCKI NINE, and radials updated due to the resurveying of KDEN (2015).</change>
	<change affected="KDEN, D01">EEONS ONE becomes EEONS TWO (very small change between EEONS and LUPTN)</change>
	<change affected="KDEN, D01">EMMYS ONE becomes EMMYS TWO</change>
	<change affected="KDEN, D01">EXTANS ONE becomes EXTANS TWO</change>
	<change affected="KDEN, D01">YOKES ONE becomes YOKES TWO</change>
	<change affected="KEGE">Deleted COTTN2 (Discontinued KEGE SID)</change>
	<change affected="KCOS">DBERRY ONE becomes DBERRY TWO</change>
	<change affected="KRAP">RCA ONE becomes RCA TWO</change>
	<change affected="KRCA">ALCOS THREE becomes ALCOS FOUR</change>
	<change affected="KGJT, D01">JNC FIVE becomes JNC SIX</change>
	<change affected="KAPA, D01">SKARF ONE becomes SKARF TWO</change>
  </version>
  <version releasedate="16 January 2013" releasetime="1358391799" airac="1301">
   <by title="Facility Engineer">Casey Diers</by>
   <packetinfo filerev="5.1" releasedate="1/16/2013">
    <filename>New Student Package v5.1</filename>
    <url>http://denartcc.org/fe/New Student Package v5.1.zip</url>
   </packetinfo>
   <sectorinfo filerev="5.1" releasedate="1/16/2013">
    <filename>ZDV ARTCC Sector v5.1</filename>
    <url>http://denartcc.org/fe/ZDV_ARTCC_Sector_5.1.zip</url>
   </sectorinfo>
   <POFinfo filerev="4.01" releasedate="5/16/2011">
    <filename>ZDV POF File v4.01</filename>
    <url>http://denartcc.org/fe/VZDVv4.01.zip</url>
   </POFinfo>
   <aliasinfo filerev="2.1.4" releasedate="1/16/2013">
    <filename>ZDV Alias File v2.1.4</filename>
    <url>http://denartcc.org/fe/zdv_alias_v2.1.4.zip</url>
   </aliasinfo>
   <change>Reordered D01 RNAV STARs to make more sense. They now start at the 12 oclock entry gate and rotate around D01 clockwise. And the correspond, so if you need to switch someone on a LN STAR to a LS STAR, you can open the menu. If they are on the third down LN STAR, you can look at the LS section, go down three, and that is the star you need to switch them to.</change>
   <change>Updated VORs, NDBs, FIXs, and Airways to 1301 AIRAC.</change>
   <change affected="D01">New SID at KDEN: YOKES ONE</change>
   <change affected="D01">New SID at KDEN: BRYCC ONE</change>
   <change affected="D01">New SID at KDEN: YOKES ONE</change>
   <change affected="D01">New SID at KDEN: EEONS ONE</change>
   <change affected="D01">New SID at KDEN: EMMYS ONE</change>
   <change affected="D01">New SID at KDEN: EXTAN ONE</change>
   <change affected="D01">New SID at KDEN: EPKEE ONE</change>
   <change affected="D01">New SID at KDEN: JMPRS ONE</change>
   <change affected="D01">New SID at KDEN: STAKR ONE</change>
   <change affected="D01">New SID at KDEN: SPAZZ ONE</change>
   <change affected="D01">New SID at KDEN: SOLAR ONE</change>
   <change affected="D01">New SID at KDEN: CONNR ONE</change>
   <change affected="D01">New SID at KDEN: COORZ ONE</change>
   <change affected="D01">New SID at KDEN: FOOOT ONE</change>
   <change affected="D01">New SID at KDEN: YAMMI ONE</change>
   <change affected="D01">KIPPR ONE becomes KIPPR TWO</change>
   <change affected="D01">New STAR at KAPA: PUFFR TWO</change>
  </version>
  <version releasedate="17 November 2012" releasetime="1353175200" airac="1212">
   <by title="Facility Engineer">Casey Diers</by>
   <packetinfo filerev="5.0" releasedate="11/17/2012">
    <filename>New Student Package v5.0</filename>
    <url>http://denartcc.org/fe/New Student Package v5.0.zip</url>
   </packetinfo>
   <sectorinfo filerev="5.0" releasedate="11/17/2012">
    <filename>ZDV ARTCC Sector 5.0</filename>
    <url>http://denartcc.org/fe/ZDV_ARTCC_Sector_5.0.zip</url>
   </sectorinfo>
   <POFinfo filerev="4.01" releasedate="5/16/2011">
    <filename>ZDV POF File v4.01</filename>
    <url>http://denartcc.org/fe/VZDVv4.01.zip</url>
   </POFinfo>
   <aliasinfo filerev="2.1.3" releasedate="6/6/2012">
    <filename>ZDV Alias File v2.1.3</filename>
    <url>http://denartcc.org/fe/zdv_alias_v2.1.3.zip</url>
   </aliasinfo>
   <change>Updated VORs, NDBs, FIXs, and Airways to 1212 AIRAC.</change>
   <change affected="D01">YELLO6 becomes YELLO7</change>
   <change affected="D01">ROCKI7 becomes ROCKI8</change>
   <change affected="D01">PLAIN4 becomes PLAIN5</change>
   <change affected="D01">TOMSN5 becomes TOMSN6</change>
   <change affected="D01">SAYGE7 becomes SAYGE8</change>
   <change affected="D01">RAMMS5 becomes RAMMS6</change>
   <change affected="D01">QUAIL6 becomes QUAIL7</change>
   <change affected="D01">POWDR7 becomes POWDR8</change>
   <change affected="D01">LARKS6 becomes LARKS7</change>
   <change affected="D01">LANDR6 becomes LANDR7</change>
   <change affected="D01">DANDD6 becomes DANDD7</change>
   <change affected="KASE">LINDZ7 becomes LINDZ8</change>
   <change affected="KASE">PITKN3 becomes PITKN4</change>
   <change affected="D01">New STAR at KDEN: ANCHR ONE</change>
   <change affected="D01">New STAR at KDEN: BOSSS ONE</change>
   <change affected="D01">New STAR at KDEN: CREDE ONE</change>
   <change affected="D01">New STAR at KDEN: FRNCH ONE</change>
   <change affected="D01">New STAR at KDEN: JAGGR ONE</change>
   <change affected="D01">New STAR at KDEN: KAILE ONE</change>
   <change affected="D01">New STAR at KDEN: KOHOE ONE</change>
   <change affected="D01">New STAR at KDEN: ANCHR ONE</change>
   <change affected="D01">New STAR at KDEN: LDORA ONE</change>
   <change affected="D01">New STAR at KDEN: MOLTN ONE</change>
   <change affected="D01">New STAR at KDEN: PEEKK ONE</change>
   <change affected="D01">New STAR at KDEN: PURRL ONE</change>
   <change affected="D01">New STAR at KDEN: TELLR ONE</change>
   <change affected="D01">New STAR at KDEN: TSHNR ONE</change>
   <change affected="D01">New STAR at KDEN: WAHUU ONE</change>
   <change affected="D01">New STAR at KDEN: ZPLYN ONE</change>
   <change affected="KCOS">New STAR at KCOS: OZZZY ONE</change>
   <change affected="D01">New STAR at KAPA: DUNNN ONE</change>
   <change affected="D01">New STAR at KAPA: SKARF ONE</change>
   <change affected="D01">New STAR at KAPA: ZOMBZ ONE</change>
  </version>
  <version releasedate="31 October 2012" releasetime="1351726181" airac="1211">
   <by title="Facility Engineer">Casey Diers</by>
   <packetinfo filerev="4.9" releasedate="10/31/2012">
    <filename>New Student Package v4.9</filename>
    <url>http://denartcc.org/fe/New Student Package v4.9.zip</url>
   </packetinfo>
   <sectorinfo filerev="4.9" releasedate="10/31/2012">
    <filename>ZDV ARTCC Sector 4.9</filename>
    <url>http://denartcc.org/fe/ZDV_ARTCC_Sector_4.9.zip</url>
   </sectorinfo>
   <POFinfo filerev="4.01" releasedate="5/16/2011">
    <filename>ZDV POF File v4.01</filename>
    <url>http://denartcc.org/fe/VZDVv4.01.zip</url>
   </POFinfo>
   <aliasinfo filerev="2.1.3" releasedate="6/6/2012">
    <filename>ZDV Alias File v2.1.3</filename>
    <url>http://denartcc.org/fe/zdv_alias_v2.1.3.zip</url>
   </aliasinfo>
   <change>Updated VORs, NDBs, FIXs, and Airways to 1211 AIRAC.</change>
   <change affected="KDEN">Added in runway lines at KDEN.  These are the overlays, so that when airport graphics are off, you can still view the runway center lines.</change>
   <change>Per Nils (ATM) Request, made the center MVAs a more predominate color, utilizing the existing taxiway color.</change>
  </version>
  <version releasedate="6 June 2012" releasetime="1339208043" airac="1206">
   <by title="Facility Engineer">Casey Diers</by>
   <packetinfo filerev="4.8" releasedate="6/6/2012">
    <filename>New Student Package v4.8</filename>
    <url>http://denartcc.org/fe/New Student Package v4.8.zip</url>
   </packetinfo>
   <sectorinfo filerev="4.8" releasedate="6/6/2012">
    <filename>ZDV ARTCC Sector 4.8</filename>
    <url>http://denartcc.org/fe/ZDV_ARTCC_Sector_4.8.zip</url>
   </sectorinfo>
   <POFinfo filerev="4.01" releasedate="5/16/2011">
    <filename>ZDV POF File v4.01</filename>
    <url>http://denartcc.org/fe/VZDVv4.01.zip</url>
   </POFinfo>
   <aliasinfo filerev="2.1.3" releasedate="6/6/2012">
    <filename>ZDV Alias File v2.1.3</filename>
    <url>http://denartcc.org/fe/zdv_alias_v2.1.3.zip</url>
   </aliasinfo>