<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE changelog [
<!ELEMENT changelog (version+)>
<!ELEMENT version (by*,facility,change+)>
<!ELEMENT facility (filename*,ID*,url*)>
<!ELEMENT filename (#PCDATA)>
<!ELEMENT ID (#PCDATA)>
<!ELEMENT url (#PCDATA)>
<!ELEMENT by (#PCDATA)>
<!ELEMENT change (#PCDATA)>
<!ATTLIST version current CDATA #IMPLIED>
<!ATTLIST version releasedate CDATA #IMPLIED>
<!ATTLIST version releasetime CDATA #IMPLIED>
<!ATTLIST by title CDATA #IMPLIED>
<!ATTLIST facility id CDATA #IMPLIED>
<!ATTLIST facility filerev CDATA #IMPLIED>
<!ATTLIST change affected CDATA #IMPLIED>
]>
 <changelog>
  <version current="1" releasedate="24 Aug 2016" releasetime="1472061600">
   <by title="Facility Engineer">James Waltz</by>
   <facility id="D01" filerev="160807">
    <filename>Denver Tracon</filename>
    <ID>D01</ID>
    <url>https://github.com/ZDV-ARTCC/ZDV_FacilityEngineering/raw/master/Releases/160807.vSTARS%20Facility%20-%20Denver%20Tracon%20(D01).gz</url>
   </facility>
   <change>Updated POF entries</change>
  </version>
  <version releasedate="27 May 2016" releasetime="1464397233">
   <by title="Facility Engineer">James Waltz</by>
   <facility id="D01" filerev="121605">
    <filename>Denver Tracon</filename>
    <ID>D01</ID>
    <url>https://github.com/ZDV-ARTCC/ZDV_FacilityEngineering/raw/master/Releases/121605.vSTARS%20Facility%20-%20Denver%20Tracon%20(D01).gz</url>
   </facility>
   <change>Updated video maps from VRC data.</change>
  </version>
  <version releasedate="26 May 2015" releasetime="1432695628">
   <by title="Facility Engineer">Casey Diers</by>
   <facility id="D01" filerev="111125">
    <filename>Denver Tracon</filename>
    <ID>D01</ID>
    <url>https://github.com/ZDV-ARTCC/ZDV_FacilityEngineering/raw/master/Releases/111125.vSTARS%20Facility%20-%20Denver%20Tracon%20(D01).gz</url>
   </facility>
   <change>Inbound Flights Listed as Over Flights Enhancement</change>
   <change>"Display Requested Altitude" option Enabled</change>
   <change>Corrected squawk codes</change>
   <change>Add RNAV Patterns for RNAV SIDs</change>
   <change>Add Scratchpad Rules for RNAV SIDs</change>
   <change>Departure Scratchpad Rules for RNAV</change>
  </version>
  <version releasedate="31 Oct 2012" releasetime="1351726181">
   <by title="Facility Engineer">Casey Diers</by>
   <facility id="D01" filerev="101453">
    <filename>Denver Tracon</filename>
    <ID>D01</ID>
    <url>http://www.denartcc.org/fe/101453.vSTARS Facility - Denver Tracon (D01).gz</url>
   </facility>
   <change>Added in several additional D01 airports so that arrivals correctly show up as arrivals instead of over-flights.</change>
  </version>
  <version releasedate="19 Feb 2012" releasetime="1329700443">
   <by title="Facility Engineer">Casey Diers</by>
   <facility id="D01" filerev="91352">
    <filename>Denver Tracon</filename>
    <ID>D01</ID>
    <url>http://www.denartcc.org/fe/91352.vSTARS Facility - Denver Tracon (D01).gz</url>
   </facility>
   <change>Allow 4 character scratch pad entries.</change>
   <change>Display requested altitudes in departure aircraft data blocks.</change>
   <change>Updated departure auto scratch pad entries so they are only set when aircraft have PLAINS, PIKES, ROCKI, or YELLO DP with a valid transition listed in their flight plan.</change>
  </version>
  <version releasedate="10 Feb 2012" releasetime="1328928080">
   <by title="Facility Engineer">Casey Diers</by>
   <facility id="D01" filerev="82046">
    <filename>Denver Tracon</filename>
    <ID>D01</ID>
    <url>http://www.denartcc.org/fe/82046.vSTARS Facility - Denver Tracon (D01).gz</url>
   </facility>
   <change affected="All">Initial Release</change>
  </version>
  <version releasedate="1 Jan 2012" releasetime="1327550400">
   <by title="Facility Engineer">Casey Diers</by>
   <facility id="D01" filerev="0">
    <filename>Denver Tracon (D01) [**Coming Soon**]</filename>
    <ID>D01</ID>
    <url>#</url>
   </facility>
   <change affected="All">Denver Tracon (D01) [**Coming Soon**]</change>
  </version>
 </changelog>
